import { Fragment, useState, type ReactNode } from "react";
import {
  Brain, Calculator, ChartBar, ChartSpline, CircleDot, Code, FileSpreadsheet,
  Handshake, Landmark, ListTodo, MonitorPlay, Presentation, Radar, Search,
  SquareSigma, TrendingUp, Tv, Workflow,
} from "lucide-react";
import "./_group.css";

const avatar = "/__l5e/assets-v1/7c5b8376-8228-4c04-a287-a33da8ee6ead/headshot.png";

const jobs = [
  ["Corporate Development Analyst", "International Matex Tank Terminals (IMTT)", "2024-04", null, "Own and build 100% of commercial DCF models and ~50% of corporate development models used to evaluate investment and commercial decisions — 40+ models spanning $50K facility upgrades to $150MM strategic initiatives, supporting 25+ deal closures and $500MM+ of capital deployment. Own a complex dock utilization model used in quarterly executive updates to guide project development and site capacity decisions. Identified a prospective customer's limited alternatives through commercial and market analysis, driving a pricing recommendation 75% above the original proposal that generated ~$12MM of incremental EBITDA. Led CRM platform selection, implementation, workflow design, automation buildout, and training, and serve as lead administrator for 20 daily users."],
  ["Senior Analyst, Analyst, Summer Intern", "Fidelis New Energy, LLC (acquired by Nscale in 2026)", "2022-08", "2024-04", "Developed project finance models for decarbonization opportunities supporting development decisions across projects representing $8B+ of combined capex. Led coordination of a $9MM grant application for CO2 transportation and storage, saving $400K+ in external consulting fees while managing procurement of 30+ documents totaling 120+ pages. Evaluated hundreds of grant opportunities across clean hydrogen/ammonia, CCS, SAF, and renewable diesel, supporting applications for over $125MM in federal grant awards. Helped develop the proprietary community benefits program used across Fidelis' projects and regularly drafted letters of support and intent for legislators, partners, and stakeholders."],
  ["Investment Analyst", "Darwin Fenner Fund", "2022-01", "2022-05", "Selected for the Large Cap Student Managed Fund ($1.5M AUM). Conducted extensive research into the Consumer Discretionary sector and built a comprehensive model using fundamental screens and relative valuations that culminated in buy and sell recommendations for the portfolio."],
  ["Equity Research Analyst", "Burkenroad Reports", "2021-01", "2021-05", "Conducted C-suite interviews, built cash flow and earnings projection models, and developed a comparable valuation methodology for Investar Bank to produce a 40-page sell-side investment report distributed to ~20,000 institutional and retail investors."],
  ["Trip Leader", "Moondance Adventures", "2022-06", "2022-08", "Led 39 students on backpacking trips through Slovenia and Croatia, responsible for logistics, safety, and group leadership in the field."],
] as const;

const ventures = [
  ["Print-on-Demand E-commerce — Bayou Bill", "Ahhh… my weird-brainchild-turned-independent-lifestyle-brand that started as a result of some late-night experimentation! What was initially a fun creative outlet evolved into a means of sending my friends unique personalized gifts inspired by shared interests. After a while, I eventually decided to launch a successful online store that generates ~$500 of passive revenue a month.\n\nBayou Bill is a 50+ product Etsy and personal website catalog run on roughly two hours of upkeep per month through automation, with a 200% YOY conversion lift from pricing, copy, and keyword strategy.\n\nRunning Bayou Bill has helped me develop hands-on skills in entrepreneurship, e-commerce, branding, and digital marketing. I've learned how to take products from concept to launch, analyze customer demand, refine listings and pricing, and build a consistent brand identity. Along the way, I've also developed practical Photoshop skills in graphic design, image editing, mockup creation, and preparing artwork for digital and physical products.\n\nMy content is largely inspired by the quirky culture of New Orleans and Mardi Gras, my love of live music, and the outdoors. I create original designs that can be printed or embroidered on virtually anything, but my main choice of merch are stickers, shirts, hats, and drinking glasses. I am constantly helping friends and family out with commissioned ideas as well!"],
  ["CardWise — Credit Card Optimization", "I manage a small credit card optimization side hustle focused on helping others get more value from their existing spending. This includes evaluating which cards best fit their spending habits, identifying worthwhile welcome offers and benefits, and helping organize rewards, credits, and annual fees so they are easier to manage.\n\nMy credit card management side hustle has taught me how to strategically evaluate rewards programs, welcome bonuses, annual fees, statement credits, and redemption options to maximize the value of everyday spending. I've developed systems to track multiple cards, benefits, deadlines, and points balances while maintaining disciplined payment habits and avoiding unnecessary fees or interest. It has also strengthened my skills in financial analysis, organization, optimization, and attention to detail by requiring me to constantly weigh costs, benefits, and opportunity tradeoffs."],
] as const;

type Interest = { name: string; description?: string; children?: Interest[] };
const interests: Interest[] = [
  { name: "Travel", description: "I love planning trips around new places, good food, and the perfect mix of adventure and relaxation. Recent highlights include Costa Rica, Belize, and Mexico City." },
  { name: "Golf", description: "I have played since I was 5 when my grandfather first snuck me onto the local range against the rules after getting tired of chasing my erratic shots around the yard. I eventually played for my high school team. Now I enjoy weekend rounds, post-work (and the occasional pre-work) range sessions, and a perpetual mission to get back to my high school form and break par for the first time!" },
  { name: "Backpacking", description: "Multi-day trips in the mountains are a special escape for me, a habit picked up as a student doing overnight trips in Rocky Mountain National Park in Colorado, the Wind River Range in Wyoming, and Pisgah National Forest in North Carolina in high school.\n\nIn college I had the privilege of backpacking through the French Alps around Chamonix and Zermatt. Post-grad, I led trips with Moondance backpacking through the Slovenian Alps. I have also done multiple trips in the Uintas in Utah and recently bagged my first 14'er in Colorado (Mt. Democrat). Up next on my backpacking bucket list are Alaska, Maine (Appalachian Trail), Zion/Canyonlands, Patagonia, and Glacier National Park." },
  { name: "Sports", description: "Football teams: Tennessee Titans, New Orleans Saints, Tulane, Vanderbilt. (Don't hold it against me for having two college teams and two NFL teams. The only way the Titans and Saints become a problem is if they meet in the Super Bowl — and I think we all know the odds of that. Same goes for Tulane and Vanderbilt meeting in the CFP…)\n\nBasketball: New Orleans Pelicans, Vanderbilt, Tulane\n\nHockey: Nashville Predators\n\nI also enjoy keeping up with F1 and most PGA Tour events. One of my annual highlights is getting to go to the Zurich Classic in New Orleans and watch players play what was my “home” course for several years." },
  { name: "Fly Fishing", description: "There is something healing about nothing but the sound of cold trickling streams early in the morning with a gentle fog slowly lifting off at the crack of dawn. I fell in love with fishing at 5 or 6 when my grandfather started taking me to a bamboo-poles-only trout farm.\n\nFast forward 5 years, my dad finally let me start messing around with his fly rod on a trip in North Carolina. I waded in the river until I was about knee deep and caught my first fish with him — a mighty 3\" rainbow trout, and I never looked back. My love of fly fishing has taken me and my dad on countless unforgettable trips and adventures. I used to tie all of my own flies in high school, and still enjoy sitting down at my work bench for a quiet evening when I return home to channel my creative side for my next adventure." },
  { name: "Live Music", description: "I am obsessed with music, although I do not play any instruments myself. I can talk your ear off about any genre, as virtually every one has been my favorite at some point in the last 10 years. Right now, my Jazz playlists own most of my attention.\n\nNew Orleans makes this an easy one to dive into — I am at as many shows and festivals as possible whenever they come through. At any given moment, I have tickets, or at least plans, for my next 3–5 shows. My ultimate favorite band is the Grateful Dead, and it has probably been several years since I went more than a day without listening to them or learning about their famous lore. If you look closely at my vibe coding portfolio page, you will see lots of easter egg references to the Dead…" },
  { name: "My Dog: Melvin", description: "I adopted Melvin in May of 2025. He is an undisclosed Dachshund mix (I think he is 75% Dachshund, 25% Beagle). He loves long walks, being my office-chair backrest during weekend work sessions, and burrowing under the covers for naps — preferably with me or my girlfriend." },
  { name: "My Family", description: "My parents split time between Nashville and Cashiers, North Carolina, where they bought what will ultimately be their retirement oasis. My dad works in sales for Rich's Foods, and my mom runs Sixth Street Creative, a consultancy firm for both residential and commercial art using local artists in Nashville.\n\nI have two younger sisters, Walker and Caroline. Walker is two years younger than me and currently works for ADP in New York. Caroline is two years younger than Walker and works for Naomi's Village in Austin." },
  { name: "Micro hobbies", children: [{ name: "Indie video games", children: [{ name: "Hades" }, { name: "Outer Wilds" }, { name: "Balatro" }, { name: "Dredge" }] }, { name: "Collecting concert posters and other music-related art" }, { name: "Longboarding" }, { name: "Testing different AI tools" }, { name: "Creating playlists for myself and friends", description: "Currently 100+ and counting — and yes, I shockingly use most of them in a given year." }, { name: "Houseplants" }, { name: "Reading" }, { name: "Training my dachshund" }, { name: "Learning how to do new things", description: "This year was vibe code, surf, drive a boat, and longboard. I'm thinking about learning how to play a synthesizer as my next mini adventure…" }, { name: "Hot Sauces", description: "I typically have a dozen in my fridge at any given time. Right now my favorites are Marie Sharpe's Habanero, Yellowbird Serrano, and Peruana Aji Yellow. I also love making my own habanero sauce." }] },
];

const photos = [
  ["/__l5e/assets-v1/1812f96c-3c3c-415e-aadc-b46030d3b4a4/travel-mountain.jpg", "Two people in an alpine field with a snow-dusted pyramidal mountain peak in the background", "Alpine travel — Matterhorn region"],
  ["/__l5e/assets-v1/582d64fd-8eaa-46ac-a0ab-c1f534df0e59/hunting-marsh.jpg", "Two people in camouflage in a boat among tall reeds at sunrise", "Duck hunting in the marsh"],
  ["/__l5e/assets-v1/61a7bda4-e334-4173-92dc-dd76734a36b4/lsu-football.jpg", "Two people posing in front of a brightly lit LSU football stadium at night", "LSU football — Saturday nights in Death Valley"],
  ["/__l5e/assets-v1/bd642f22-e828-4e75-a77d-b34848c4254c/winter-bridge.jpg", "A couple sitting on a bridge railing over water with snow-dusted evergreen forest behind", "Winter outing"],
  ["/__l5e/assets-v1/f05a3f4d-17c6-4ae0-9ffc-f5b963b7a479/jazz-fest.jpg", "A couple in the crowd at the New Orleans Jazz Fest festival stage", "Jazz Fest — New Orleans"],
  ["/__l5e/assets-v1/ce74388d-bd82-4536-88fa-57771c8f0807/fly-fishing.jpg", "A man holding a silver bonefish on a skiff in calm water", "Fly fishing for bonefish — Belize"],
] as const;

const linkMap: Record<string, string> = { IMTT: "https://imtt.com/", Fidelis: "https://www.fidelisnewenergy.com/", Nscale: "https://www.nscale.com" };
function LinkedText({ children }: { children: string }) {
  return children.split(/(Fidelis|Nscale|IMTT)/g).map((part, i) => linkMap[part] ? <a key={i} href={linkMap[part]} target="_blank" rel="noopener noreferrer" className="underline decoration-foreground/40 underline-offset-4 hover:decoration-foreground transition-colors">{part}</a> : <Fragment key={i}>{part}</Fragment>);
}

function SplitSection({ title, id, children }: { title: string; id: string; children: ReactNode }) {
  return <section id={id} className="flex items-center px-8 md:px-16 lg:px-24 py-20 md:py-24"><div className="w-full max-w-7xl mx-auto grid grid-cols-1 md:grid-cols-[1fr_2fr] lg:grid-cols-[1fr_1.5fr] gap-12 md:gap-24 lg:gap-32 items-start"><div className="md:text-left flex items-start md:sticky md:top-32"><h2 className="text-section">{title}</h2></div><div>{children}</div></div></section>;
}

function CollapsibleText({ description }: { description: string }) {
  const [open, setOpen] = useState(false);
  const paragraphs = description.split("\n\n").map((p) => p.trim()).filter(Boolean);
  const first = paragraphs[0] ?? ""; const tooLong = first.length > 220;
  return <div className="space-y-3"><p className="text-body leading-relaxed">{!open && tooLong ? `${first.slice(0, 220).trimEnd()}…` : first}</p>{open && paragraphs.slice(1).map((p, i) => <p key={i} className="text-body leading-relaxed">{p}</p>)}<button type="button" onClick={() => setOpen(!open)} aria-expanded={open} className="text-small underline underline-offset-4 hover:opacity-70 transition-opacity">{open ? "Read less" : "Read more"}</button></div>;
}

function InterestNode({ node, depth = 0 }: { node: Interest; depth?: number }) {
  const [open, setOpen] = useState(false); const collapsible = !!node.description || !!node.children?.length;
  const nameClass = depth === 0 ? "text-large leading-tight" : depth === 1 ? "text-body leading-tight" : "text-small leading-tight";
  const indent = depth === 1 ? "pl-4" : depth > 1 ? "pl-8" : "";
  if (!collapsible) return <div className={`border-b border-dashed border-line/40 last:border-0 ${indent}`}><p className={`py-2 ${nameClass}`}>{node.name}</p></div>;
  return <div className={`border-b border-dashed border-line/40 last:border-0 ${indent}`}><button type="button" onClick={() => setOpen(!open)} aria-expanded={open} className="flex w-full items-center justify-between gap-3 py-2 text-left transition-opacity hover:opacity-70"><h3 className={nameClass}>{node.name}</h3><span className="text-small shrink-0 opacity-60">{open ? "−" : "+"}</span></button>{open && <div className="space-y-1 pb-3">{node.description?.split("\n\n").map((p, i) => <p key={i} className="text-body leading-relaxed">{p}</p>)}{node.children && <div className="space-y-1">{node.children.map((child) => <InterestNode key={child.name} node={child} depth={depth + 1} />)}</div>}</div>}</div>;
}

const skillIcons = [Calculator, TrendingUp, Landmark, Handshake, Search, ChartSpline, Presentation, Workflow, FileSpreadsheet, SquareSigma, Brain, Tv, Radar, ChartBar, Code, MonitorPlay, ListTodo];
const skills = "Financial Modeling, DCF Valuation, Project Finance, Business Development, Market Research & Intelligence, Investment Analysis, Executive Presentations, Process Improvement, Excel, Macabacus, Capital IQ, Bloomberg, Vortexa, Tableau, Python, PowerPoint, Microsoft Project".split(", ");

export function Current() {
  return <div className="min-h-screen bg-background">
    <a href="#main-content" className="sr-only focus:not-sr-only focus:absolute focus:top-4 focus:left-4 focus:z-50 focus:px-4 focus:py-2 focus:bg-primary focus:text-primary-foreground focus:rounded-md">Skip to main content</a>
    <main id="main-content">
      <nav className="fixed top-0 left-0 right-0 z-50 bg-background/80 backdrop-blur-sm border-b border-border px-8 md:px-16 lg:px-24" aria-label="Main navigation"><div className="max-w-7xl mx-auto py-3"><div className="flex items-center justify-between gap-4"><a href="#" className="flex flex-col sm:flex-row sm:items-center gap-1 sm:gap-4"><span className="text-base sm:text-lg md:text-xl lg:text-2xl font-bold">James McKnight</span><span className="text-sm sm:text-base md:text-lg lg:text-xl font-semibold text-muted-foreground">Corporate Development Analyst at IMTT</span></a><div className="flex items-center gap-4 sm:gap-6"><a href="/projects" className="text-base sm:text-lg md:text-xl lg:text-2xl font-semibold hover:text-muted-foreground transition-colors">Passion Projects</a><a href="#contact" className="text-base sm:text-lg md:text-xl lg:text-2xl font-semibold hover:text-muted-foreground transition-colors">Contact</a></div></div></div></nav>
      <section className="flex items-center justify-center px-8 md:px-16 lg:px-24 pt-24 pb-12 md:pt-28 md:pb-14"><div className="w-full max-w-7xl"><div className="text-center mb-12 md:mb-16"><p className="text-tiny tracking-widest"><LinkedText>Corporate Development Analyst at IMTT</LinkedText></p></div><div className="grid grid-cols-1 lg:grid-cols-3 gap-12 lg:gap-16 items-center"><div className="text-center lg:text-right"><h1 className="text-display lg:text-[9rem] leading-none font-light lg:font-normal">James</h1></div><div className="flex flex-col items-center"><img src={avatar} alt="James McKnight" className="w-full max-w-[52rem] h-auto aspect-[52/60] object-cover rounded-t-[160px]" /></div><div className="text-center lg:text-left"><h1 className="text-display lg:text-[9rem] leading-none font-light lg:font-normal">McKnight</h1></div></div><div className="text-center mt-10 md:mt-14"><h2 className="text-[2.5rem] md:text-[3.5rem] lg:text-[4rem] leading-none font-light tracking-tight">New Orleans, Louisiana</h2></div><div className="text-center mt-8 md:mt-10"><p className="text-small">{new Date().getFullYear()}</p></div></div></section>
      <section id="about" className="flex items-center justify-center px-8 md:px-16 lg:px-24 pt-10 md:pt-12 pb-16 md:pb-20"><div className="w-full max-w-4xl text-center space-y-10 md:space-y-12"><h2 className="text-tiny tracking-widest">ABOUT ME</h2><div className="text-body leading-relaxed max-w-3xl mx-auto"><LinkedText>{"I'm a corporate development analyst focused on turning complex commercial and financial questions into clear investment decisions. I own the DCF and corporate development models used to evaluate opportunities across IMTT's terminal network — from $50K facility upgrades to $150MM strategic initiatives — work that has supported 25+ deal closures and $500MM+ of capital deployment."}</LinkedText></div></div></section>
      <SplitSection title="Professional Experience" id="work"><div className="space-y-16 md:space-y-20">{jobs.map(([role, company, start, end, description], index) => <div key={company}>{index > 0 && <hr className="border-t border-foreground/15 mb-16 md:mb-20" />}<div className="space-y-3"><h3 className="text-large leading-tight"><LinkedText>{`${role} at ${company}`}</LinkedText></h3><p className="text-small">{new Date(start).getFullYear()} - {end ? new Date(end).getFullYear() : "Present"}</p><div className="text-body leading-relaxed mt-6"><LinkedText>{description}</LinkedText></div></div></div>)}</div></SplitSection>
      <SplitSection title="Side Ventures" id="side-ventures"><div className="space-y-10 md:space-y-12">{ventures.map(([name, description]) => <div key={name} className="space-y-2"><h3 className="text-large leading-tight">{name}</h3><CollapsibleText description={description} /></div>)}</div></SplitSection>
      <SplitSection title="Education" id="education"><div className="space-y-16 md:space-y-20"><div className="space-y-3"><p className="text-large leading-tight">Bachelor of Science Management — Double Major in Finance and Legal Studies in Business, Tulane University, A. B. Freeman School of Business</p><p className="text-small">2018 - 2022</p><div className="text-body mt-4">GPA: 3.7</div></div></div></SplitSection>
      <SplitSection title="Skills" id="skills"><ul className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-x-8 gap-y-4 list-none p-0">{skills.map((skill, index) => { const Icon = skillIcons[index] ?? CircleDot; return <li key={skill} className="flex items-center gap-3 text-small text-foreground"><Icon size={18} className="shrink-0 text-accent" strokeWidth={2} /><span>{skill}</span></li>; })}</ul></SplitSection>
      <SplitSection title="Interests" id="interests"><div className="space-y-2 md:space-y-3">{interests.map((interest) => <InterestNode key={interest.name} node={interest} />)}</div></SplitSection>
      <section id="photos" className="px-8 md:px-16 lg:px-24 py-20 md:py-24"><div className="max-w-7xl mx-auto"><div className="md:sticky md:top-32 mb-10 md:mb-16"><h2 className="text-section">In Focus</h2></div><div className="columns-2 md:columns-3 gap-3 md:gap-4 [column-fill:balance]">{photos.map(([src, alt, caption]) => <figure key={src} className="group relative mb-3 md:mb-4 break-inside-avoid overflow-hidden border border-foreground/15"><img src={src} alt={alt} loading="lazy" className="w-full h-auto block transition-transform duration-500 group-hover:scale-[1.03]" onError={(event) => { event.currentTarget.classList.add("hidden"); event.currentTarget.nextElementSibling?.classList.remove("hidden"); }} /><div className="hidden aspect-[4/3] w-full items-center justify-center bg-secondary p-6 text-center"><span className="text-small leading-tight">{caption}</span></div><figcaption className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/70 to-transparent p-3 md:p-4"><span className="text-tiny text-white/90 leading-tight">{caption}</span></figcaption></figure>)}</div></div></section>
      <section id="contact" className="flex items-center px-8 md:px-16 lg:px-24 py-20 md:py-24"><div className="w-full max-w-7xl mx-auto grid grid-cols-1 lg:grid-cols-[1fr_1.5fr] gap-12 lg:gap-32 items-center"><div className="flex items-center justify-center lg:justify-end lg:pr-16 lg:border-r border-foreground/15"><h2 className="text-section">Contact</h2></div><div className="flex items-center lg:pl-16"><div className="space-y-6"><div className="mb-10"><img src={avatar} alt="James McKnight" className="w-48 h-64 object-cover" /></div><p className="text-large">James McKnight</p><a href="mailto:jrmcknight08@gmail.com" className="text-body underline block">jrmcknight08@gmail.com</a><a href="https://www.linkedin.com/in/james-r-mcknight" target="_blank" rel="noopener noreferrer" className="text-body underline block">www.linkedin.com/in/james-r-mcknight</a></div></div></div></section>
    </main>
    <footer className="max-w-[660px] mx-auto px-6 py-8 mt-16"><div className="timeline-meta">© {new Date().getFullYear()} All rights reserved.</div></footer>
  </div>;
}