// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/portfolio-improvement/Current.tsx": () => import("../components/mockups/portfolio-improvement/Current.tsx"),
  "./components/mockups/portfolio-improvement/Improved.tsx": () => import("../components/mockups/portfolio-improvement/Improved.tsx")
};
